default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: chardham_parivahan_development
  username: postgres
  password: nikhil

test:
  <<: *default
  database: chardham_parivahan_test
  username: postgres
  password: nikhil
  host: localhost

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
